# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-23 03:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_name', models.CharField(max_length=128, unique=True)),
                ('case_description', models.CharField(max_length=500)),
                ('case_created', models.DateTimeField(verbose_name='Date created')),
                ('case_modified', models.DateTimeField(verbose_name='Date modified')),
                ('case_slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_month', models.IntegerField()),
                ('day_of_week', models.CharField(max_length=3)),
            ],
            options={
                'verbose_name_plural': 'schedule',
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_name', models.CharField(max_length=128, unique=True)),
                ('step_created', models.DateTimeField(verbose_name='Date created')),
                ('step_modified', models.DateTimeField(verbose_name='Date modified')),
                ('step_slug', models.SlugField(unique=True)),
                ('always_run', models.IntegerField(default=0)),
                ('action', models.CharField(max_length=128)),
                ('arg1', models.CharField(max_length=128)),
                ('arg2', models.CharField(max_length=128)),
                ('arg3', models.CharField(max_length=128)),
                ('message', models.CharField(max_length=128)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testPenguin.Case')),
            ],
        ),
        migrations.CreateModel(
            name='Suite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suite_name', models.CharField(max_length=128, unique=True)),
                ('suite_description', models.CharField(max_length=500)),
                ('suite_created', models.DateTimeField(verbose_name='Date created')),
                ('suite_modified', models.DateTimeField(verbose_name='Date modified')),
                ('suite_slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='timeOfDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeOfDay', models.IntegerField()),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testPenguin.Schedule')),
            ],
        ),
        migrations.AddField(
            model_name='schedule',
            name='suite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testPenguin.Suite'),
        ),
        migrations.AddField(
            model_name='case',
            name='suite',
            field=models.ManyToManyField(to='testPenguin.Suite'),
        ),
    ]
