# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-09 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testPenguin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='step_type',
            field=models.CharField(default='action', max_length=128),
        ),
        migrations.AlterField(
            model_name='case',
            name='suite',
            field=models.ManyToManyField(blank=True, to='testPenguin.Suite'),
        ),
    ]
