# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-23 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testPenguin', '0005_remove_step_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='arg1',
        ),
        migrations.RemoveField(
            model_name='step',
            name='arg2',
        ),
        migrations.RemoveField(
            model_name='step',
            name='arg3',
        ),
        migrations.AddField(
            model_name='step',
            name='locator',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='step',
            name='locator_type',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='step',
            name='value',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
