# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-23 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testPenguin', '0006_auto_20160923_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='step_order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
