# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-27 03:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testPenguin', '0007_step_step_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='step_created',
        ),
        migrations.RemoveField(
            model_name='step',
            name='step_modified',
        ),
    ]
