# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-27 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testPenguin', '0008_auto_20160927_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='step_name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='step',
            name='step_slug',
            field=models.SlugField(),
        ),
    ]
